### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by nicolasdeory** [RoyaleAPI/cr-api-docs#10]
Many JSON response examples from the documentation are outdated or missing information. I'd like to see updated especially the player and clan JSON responses.

**Comment by fourjr** [comment]
Pretty sure all of those are up to date. Could you give an example?

**Comment by nicolasdeory** [comment]
For instance, AFAIK chest cycle and player battles are no longer included in endpoint `/player`, but they are shown in the sample JSON response. I would like to be sure of what's included exactly.

**Comment by fourjr** [comment]
Currently, at time of writing, chests and battles are still in /player.
