### ISSUE TITLE
/auth/stats endpoint needs listed as reenabled in docs

### ISSUE THREAD

**Issue by BlackHoleFox** [RoyaleAPI/cr-api-docs#25]
In the Discord server, Selfish announced that the /auth/stats is now active again. The docs currently say differently

![image](https://user-images.githubusercontent.com/20936452/40089465-68f3a962-589b-11e8-8093-82befe20f1d7.png)

**Comment by fourjr** [comment]
try using it :)

**Comment by fourjr** [comment]
```json
{
  "error": true,
  "status": 503,
  "message": "Temporarily Unavailable | Additional information and support: http:\/\/discord.me\/royaleapi"
}
```
