### ISSUE TITLE
Bad links in War endpoints

### ISSUE THREAD

**Issue by munsterlander** [RoyaleAPI/cr-api-docs#28]
On this page:

https://docs.royaleapi.com/#/endpoints/clan_war

The collection day and war day full JSON responses are backwards.

On this page:

https://docs.royaleapi.com/#/endpoints/clan_warlog

The full JSON response is the same as the one for the previous page. https://docs.royaleapi.com/json/clan_war_9LPVG9UC.json and as such, doesn't have all the data.

**Comment by fourjr** [comment]
Thanks, for the clan war log url, you can use https://docs.royaleapi.com/json/clan_warlog_9PJ82CRC.json for now

Note to self: header for war log misleading

**Comment by jegfish** [comment]
The JSON outline/not full response at https://docs.royaleapi.com/#/endpoints/clan_warlog is also invalid JSON.

```json
[
    "createdDate": number,
    {"participants": ...},
    {"standings": ...},
    {"seasonNumber": number}
]
```

`"createdDate": number` is invalid, and the rest just looks weird to me but I don't know if that's how it's supposed to be.

**Comment by fourjr** [comment]
That's just an outline, use the link I sent above to see the actual response
