### ISSUE TITLE
Statistics Clan

### ISSUE THREAD

**Issue by camaleir** [RoyaleAPI/cr-api-docs#33]
- Name of app (statistics clans)
- Link to Name of app (http://andrestapia.000webhostapp.com/clash.php?tag_clan=90purqrq)
- Author(s) of app (andres tapia)
- Link(s) to author(s) of app (http://andrestapia.000webhostapp.com)
- Discord username(s) of author(s) <porkeno>
- Description (to get clan statistics)

**Comment by fourjr** [comment]
Could you be more descriptive regarding your application?

**Comment by fourjr** [comment]
Closed as stale.
