### ISSUE TITLE
Chest Tracker

### ISSUE THREAD

**Issue by ssPerman01** [RoyaleAPI/cr-api-docs#34]
- Name of app: chest tracker
- Link to Name of app: after publish app to store, we will send link for you.
- Author(s) of app: AnhNT, LongLD
- Link(s) to author(s) of app: https://github.com/ssPerman01
- Discord username(s) of author(s)
- Description: We want build app android (maybe both IOS):
 + check chest for user
 + open tourament
 + clan statistics

**Comment by ssPerman01** [comment]
@fourjr please review my issues

**Comment by bsantosh909** [comment]
It really an bad idea to make comments with mention just to ask to review the app.

He will for sure review when he gets free time. Just have some patience.

**Comment by fourjr** [comment]
Please make your application public and published before asking for it to be added to showcase.

Edit + comment once you have done so.
