### ISSUE TITLE
Incorrect query string parameter name

### ISSUE THREAD

**Issue by jegfish** [RoyaleAPI/cr-api-docs#40]
In [this table](https://docs.royaleapi.com/#/endpoints/player_verification?id=query-string-parameters) in the Player Verification endpoint the parameter is listed as `PLAYER_API_TOKEN` when the parameter's name is actually just `token`.

**Comment by fourjr** [comment]
Read the url, `?token=<PLAYER_API_TOKEN>`

`PLAYER_API_TOKEN` is used like a variable name so we can better explain what it means

`player ` is just for clarity

**Comment by jegfish** [comment]
I find this confusing and strange as all other endpoints that take extra query string parameters have tables using the actual names of the parameters.

- [Clan Search](https://docs.royaleapi.com/#/endpoints/clan_search?id=query-string-parameters)
- [Clan Battles](https://docs.royaleapi.com/#/endpoints/clan_battles?id=query-string-parameters)
- [Clan History](https://docs.royaleapi.com/#/endpoints/clan_history?id=query-string-parameters)
- [Clan Weekly History](https://docs.royaleapi.com/#/endpoints/clan_history_weekly?id=query-string-parameters)
- [Open Tournaments](https://docs.royaleapi.com/#/endpoints/tournaments_open?id=query-string-parameters) and other similar tournament endpoints.
- [Tournaments Search](https://docs.royaleapi.com/#/endpoints/tournaments_search?id=query-string-parameters)

I don't believe using a different name in the table is necessary as if more explanation is needed the `Description` column is used. It just adds inconsistency and confusion.

**Comment by fourjr** [comment]
good catch, will fix
