### ISSUE TITLE
x-ratelimit-retry-after units

### ISSUE THREAD

**Issue by ThomasDK81** [RoyaleAPI/cr-api-docs#44]
After testing my error handling, I noticed that x-ratelimit-retry-after is in what looks like microseconds.
The docs says seconds ([https://docs.royaleapi.com/#/faq](https://docs.royaleapi.com/#/faq)).

Testing in Postman I get:
```
x-ratelimit-limit →5
x-ratelimit-remaining →0
x-ratelimit-retry-after →129
```

Right after, I request again and I get:
```
x-ratelimit-limit →5
x-ratelimit-remaining →4
```

**Comment by ThomasDK81** [comment]
You changed it to milliseconds. I believe its microseconds.

The difference is:
1 sec = 1000 milisec = 1000000 microsec

**Comment by fourjr** [comment]
@selfish please comment
